ifeq ($(CPU_EN), y)
    PM_SRC += dev/cpu/cpu.c 
    PM_SRC += dev/cpu/clock_cpu.c 
    PM_SRC += dev/cpu/regulator_cpu.c 
    PM_SRC += dev/cpu/opp_cpu.c 
    PM_SRC += dev/cpu/avs_cpu.c 
endif

ifeq ($(MEDIA_EN), y)
    PM_SRC += dev/media/media.c
    PM_SRC += dev/media/clock_media.c
    PM_SRC += dev/media/regulator_media.c
    PM_SRC += dev/media/opp_media.c
    PM_SRC += dev/media/avs_media.c
endif
